GET http://localhost:8080/api/testdriver

###
POST http://localhost:8080/api/drivers
Content-Type: application/json

{
  "firstname": "Frank",
  "lastname": "Galager",
  "age": "48"
}

###
GET http://localhost:8080/api/testcar

###
GET http://localhost:8080/api/drivers