GET http://localhost:8082/api/testdriver

###
POST http://localhost:8082/api/drivers
Content-Type: application/json

{
  "firstName": "Frank",
  "lastName": "Galager",
  "age": "48"
}

###
GET http://localhost:8082/api/testcar

###
GET http://localhost:8082/api/drivers